class EnvConfig:

    #CLOUD CONFIG
    CLOUD_TRANSMISSION_POWER = 10e9
    CLOUD_FIBER_DISTANCE = 50.0

    #OPTICAL FIBER CONFIG
    OPTICAL_FIBER_REFRACTIVE_INDEX = 1.5
    OPTICAL_FIBER_FEC = 0.20
    OPTICAL_FIBER_OVERHEAD = 0.10
    OPTICAL_FIBER_WDM = 16
    OPTICAL_FIBER_CAPACITY = 100e9

    #MEC CONFIG
    MEC_MAX_COMPUTATION_RESOURCES = 1e9
    MEC_TRANSMISSION_POWER = 100

    #BS CONFIG
    BS_TOTAL_CHANNEL_BANDWIDTH = 100e6
    BS_NOISE = 1e-10
    BS_SHADOW_SIGMA_DB = 5.9

    #UE CONFIG
    NUM_UES = 20
    UE_MAX_COMPUTATION_RESOURCES = 40e6
    UE_KAPPA = 1e-21
    UE_RESIDUAL_J_PER_T = 0.1
    UE_MAX_BATTERY = 4000
    UE_TRANSMISSION_POWER = 1
    UE_CARRIER_FREQUENCY = 3.5

    #QoE CONFIG
    FAIL_PENALTY = -0.1 # η

    #SIMULATION
    TOTAL_TIME_T = 2000
    TASK_ARRIVAL_RATE = 10
